language: ruby
rvm:
- 2.1

cache: bundle

install: gem install jekyll jekyll-paginate jekyll-sitemap html-proofer

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: jekyll build && htmlproofer ./_site --allow_hash_href=true --assume_extension=true

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

notifications:
  email:
    recipients:
      - smurfdad@smurfdad.es
      
sudo: false # route your build to the container-based infrastructure for a faster build