# Site settings
title: Smurf_Dad
subtitle: Mi pequeño rincón en el ciber espacio
author: Smurf Dad
email: smurfdad@smurfdad.es
description: > # this means to ignore newlines until "baseurl:"
  Informática, Personal, Alergia Proteínas Leche Vaca, APLV,  Ideas, Opinión, Coordenadas GPS, programación, Java, Tecnología
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smurfdad.es" # the base hostname & protocol for your site
twitter_username: Smurf_Dad
github_username: smurfdad

# Build settings
markdown: kramdown
paginate_path: page/:num
paginate: 10
show_drafts: false
future: false
permalink: /:year/:month/:title.html
timezone: Europe/Madrid
google-analytics: UA-637317-4

gems: [jekyll-paginate, jekyll-gist]